title: Alex's Thoughts Archive
author: Alex
email: me@alxwnth.com
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

kramdown:
  input: GFM
permalink: pretty

plugins:
  - jekyll-sitemap

exclude: ["LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "script"]

permalink: /:year/:month/:day/:title/