title: Alex's Thoughts Archive
author: Alex
email: me@alxwnth.com
description: >-
  I have something to say so I say it.
baseurl: "" # the subpath of your site, e.g. /blog
url: "" # the base hostname & protocol for your site, e.g. http://example.com

kramdown:
  input: GFM
permalink: pretty

disqus_shortname: 

github: https://github.com/alxwnth
twitter: http://twitter.com/alxwnth

plugins:
  - jekyll-sitemap

exclude: ["LICENSE", "README.md", "CNAME", "vendor", "Gemfile", "script"]

permalink: /:year/:month/:day/:title/